# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='badge',
            field=models.ImageField(upload_to='budge/'),
        ),
    ]
