# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('date', models.EmailField(max_length=254)),
                ('student_awarded', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
