# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='student_name',
        ),
    ]
