# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0002_auto_20191117_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='date',
        ),
        migrations.AddField(
            model_name='awards',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
