# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0003_auto_20191117_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prizes.Awards')),
            ],
        ),
    ]
