# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schoo_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
