# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0005_auto_20191117_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
    ]
